# -*- coding: utf-8 -*-
"""
Scenario Data Model and G.4.5.1 Adapter for G.4.5.2 Strategy Scenario Builder.
"""

from dataclasses import dataclass, field
from typing import List, Dict, Any, Tuple
from ml.strategy.stint import Stint
from ml.strategy.pit_stop import PitStop
from ml.strategy.race_config import RaceConfig
from ml.strategy.scenario_id import generate_canonical_key, generate_deterministic_scenario_id


@dataclass
class Scenario:
    """
    Representation of a candidate race strategy scenario generated by G.4.5.2.

    Attributes:
        scenario_id: Deterministic hash ID (e.g. SCN_a8f3b9c1d2e4).
        race_id: Race configuration identifier.
        total_laps: Total race distance in laps.
        starting_compound: Initial tire compound mounted at race start.
        compound_sequence: Sequential list of mounted tire compounds per stint.
        stints: Ordered list of G.4.5.1 Stint instances.
        pit_stops: Ordered list of G.4.5.1 PitStop instances.
        number_of_stops: Total pit stops completed (len(pit_stops)).
        number_of_stints: Total stints completed (len(stints)).
        generation_method: Algorithm strategy used ("BOUNDED_GRID", "EXHAUSTIVE", etc.).
        validation_status: "VALID" or "INVALID".
        validation_errors: List of constraint validation warning messages.
        generation_metadata: Contextual dictionary (config params, timestamps, bounds).
    """
    scenario_id: str
    race_id: str
    total_laps: int
    starting_compound: str
    compound_sequence: List[str]
    stints: List[Stint]
    pit_stops: List[PitStop]
    number_of_stops: int
    number_of_stints: int
    generation_method: str = "BOUNDED_GRID"
    validation_status: str = "VALID"
    validation_errors: List[str] = field(default_factory=list)
    generation_metadata: Dict[str, Any] = field(default_factory=dict)

    def __post_init__(self):
        """Validate scenario properties."""
        self.starting_compound = str(self.starting_compound).upper()
        self.compound_sequence = [str(c).upper() for c in self.compound_sequence]

        if self.total_laps <= 0:
            raise ValueError(f"total_laps must be > 0, got {self.total_laps}")
        if self.number_of_stops != len(self.pit_stops):
            raise ValueError(
                f"number_of_stops ({self.number_of_stops}) does not match pit_stops count ({len(self.pit_stops)})"
            )
        if self.number_of_stints != len(self.stints):
            raise ValueError(
                f"number_of_stints ({self.number_of_stints}) does not match stints count ({len(self.stints)})"
            )

    @property
    def canonical_key(self) -> str:
        """Computes canonical stint string representation."""
        return generate_canonical_key(self.stints)

    def get_compound_for_lap(self, lap: int) -> str:
        """Retrieves mounted tire compound for a given race lap."""
        if not (1 <= lap <= self.total_laps):
            raise ValueError(f"Lap {lap} out of bounds for total_laps {self.total_laps}")
        for stint in self.stints:
            if stint.start_lap <= lap <= stint.end_lap:
                return stint.compound
        raise ValueError(f"No stint covers lap {lap}")

    def to_g451_payload(self, pit_stop_loss_sec: float = 22.5, starting_fuel: float = None) -> Tuple[List[Stint], List[PitStop], RaceConfig]:
        """
        Adapter returning G.4.5.1 StrategySimulator input tuple: (stints, pit_stops, race_config).
        """
        init_fuel = starting_fuel if starting_fuel is not None else self.stints[0].starting_fuel
        config = RaceConfig(
            race_id=self.race_id,
            total_laps=self.total_laps,
            starting_fuel=init_fuel,
            initial_compound=self.starting_compound,
            pit_stop_loss_sec=pit_stop_loss_sec,
        )
        return self.stints, self.pit_stops, config

    def to_dict(self) -> Dict[str, Any]:
        """Serializes scenario object to full dictionary."""
        return {
            "scenario_id": self.scenario_id,
            "race_id": self.race_id,
            "total_laps": self.total_laps,
            "starting_compound": self.starting_compound,
            "compound_sequence": self.compound_sequence,
            "canonical_key": self.canonical_key,
            "number_of_stops": self.number_of_stops,
            "number_of_stints": self.number_of_stints,
            "stints": [s.to_dict() for s in self.stints],
            "pit_stops": [p.to_dict() for p in self.pit_stops],
            "generation_method": self.generation_method,
            "validation_status": self.validation_status,
            "validation_errors": self.validation_errors,
            "generation_metadata": self.generation_metadata,
        }
